AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ImageService

Parameters:

  StageEnv:
    Type: String
    Default: staging
    AllowedValues:
      - test
      - development
      - staging
      - production

Resources:

  ImageServiceLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lib/image_service.handler
      Runtime: ruby2.7
      Timeout: 60
      MemorySize: 512
      FunctionName: !Sub image-service-${StageEnv}
      Environment:
        Variables:
          STAGE_ENV: !Ref StageEnv
          RUBYOPT: '-W0'

Outputs:

  ImageServiceLambdaArn:
    Description: Lambda Function Arn
    Value: !GetAtt ImageServiceLambda.Arn
  
